"""add department to users

Revision ID: bfd0c35d55ba
Revises: a05b3668cc91
Create Date: 2026-07-24 05:25:07.787843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd0c35d55ba'
down_revision: Union[str, Sequence[str], None] = 'a05b3668cc91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True))

    op.execute("UPDATE users SET department = 'Unknown' WHERE department IS NULL")

    op.alter_column('users', 'department', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department')
    # ### end Alembic commands ###
